/**
 * Verification Script: Test that the offline lab can decrypt keys generated by the admin dashboard.
 * 
 * This script:
 * 1. Loads .env from the offline_lab_1 project
 * 2. Reads the LICENSE_SECRET_SALT from both projects
 * 3. Generates a test license key using the admin dashboard's method
 * 4. Decrypts it using the offline lab's method
 * 5. Verifies they match
 */
const path = require('path');
const crypto = require('crypto');

// Load .env from offline_lab_1
require('dotenv').config({ path: path.join(__dirname, '.env') });

const SALT_FROM_ENV = process.env.LICENSE_SECRET_SALT;
const SALT_FALLBACK = 'Musharraf_709121SaltKey';
const SALT_USED = SALT_FROM_ENV || SALT_FALLBACK;

console.log('=== LICENSE KEY CROSS-COMPATIBILITY TEST ===\n');
console.log(`LICENSE_SECRET_SALT from .env: "${SALT_FROM_ENV}"`);
console.log(`Salt being used: "${SALT_USED}"`);
console.log(`Using fallback? ${!SALT_FROM_ENV}\n`);

if (!SALT_FROM_ENV) {
  console.error('❌ CRITICAL: .env not loaded! LICENSE_SECRET_SALT is undefined.');
  console.error('   The fallback salt will be used, which does NOT match the admin dashboard.');
  process.exit(1);
}

// === ADMIN DASHBOARD METHOD (encrypt) ===
function adminEncrypt(machineId, expirationDate) {
  const KEY = crypto.createHash('sha256').update(SALT_USED).digest();
  const payload = `${machineId}|${expirationDate}`;
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv('aes-256-cbc', KEY, iv);
  let encrypted = cipher.update(payload, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return (iv.toString('hex') + encrypted).toUpperCase();
}

// === OFFLINE LAB METHOD (decrypt) ===
function offlineDecrypt(licenseKey) {
  try {
    const KEY = crypto.createHash('sha256').update(SALT_USED).digest();
    const cleanKey = licenseKey.trim().toLowerCase();
    if (cleanKey.length <= 32) return null;
    
    const ivHex = cleanKey.substring(0, 32);
    const encryptedHex = cleanKey.substring(32);
    
    const iv = Buffer.from(ivHex, 'hex');
    const decipher = crypto.createDecipheriv('aes-256-cbc', KEY, iv);
    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    const parts = decrypted.split('|');
    if (parts.length === 2) {
      return { machineId: parts[0], expiryDate: parts[1] };
    }
  } catch (e) {
    console.error('Decryption failed:', e.message);
  }
  return null;
}

// === TEST ===
const testMachineId = '0c580b5c-44ee-45c0-a060-3d234fac6514';
const testExpiry = '2027-06-03T05:50:00.000Z';

console.log('--- Test Data ---');
console.log(`Machine ID: ${testMachineId}`);
console.log(`Expiry Date: ${testExpiry}\n`);

const licenseKey = adminEncrypt(testMachineId, testExpiry);
console.log(`Generated License Key: ${licenseKey}\n`);

const decrypted = offlineDecrypt(licenseKey);

if (decrypted) {
  console.log('✅ Decryption SUCCEEDED!');
  console.log(`   Machine ID: ${decrypted.machineId}`);
  console.log(`   Expiry Date: ${decrypted.expiryDate}`);
  
  if (decrypted.machineId === testMachineId && decrypted.expiryDate === testExpiry) {
    console.log('\n✅ ALL VALUES MATCH! License system is working correctly.');
  } else {
    console.log('\n❌ Values do NOT match after decryption!');
  }
} else {
  console.log('❌ Decryption FAILED! This is the "Invalid license key format or signature" error.');
}
