/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  labInfo: {
    fontSize: 10,
    color: '#666',
  },
  patientSection: {
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  table: {
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableColHeader: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    backgroundColor: '#f3f4f6',
  },
  tableCol: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCell: {
    margin: 5,
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: 'grey',
    fontSize: 10,
  },
  signatureSection: {
    marginTop: 50,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  signature: {
    textAlign: 'center',
    width: 150,
    borderTopWidth: 1,
    paddingTop: 5,
  }
});

export const ReportPDF = ({ order, labSettings }: { order: any, labSettings: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>{labSettings?.labName || 'Pathology Laboratory'}</Text>
          <Text style={styles.labInfo}>{labSettings?.address || '123 Medical Hub, India'}</Text>
        </View>
        <View>
          <Text style={styles.labInfo}>NABL: {labSettings?.nablNo || 'NABL-12345'}</Text>
        </View>
      </View>

      <View style={styles.patientSection}>
        <View>
          <Text>Patient Name: {order?.patient?.name || 'John Doe'}</Text>
          <Text>Age/Sex: {order?.patient?.age || '30'} {order?.patient?.ageUnit || 'Y'} / {order?.patient?.gender || 'Male'}</Text>
          <Text>PID: {order?.patient?.patientId || 'LAB-2026-0001'}</Text>
        </View>
        <View>
          <Text>Registered: {order?.createdAt ? new Date(order.createdAt).toLocaleDateString() : 'N/A'}</Text>
          <Text>Order No: {order?.orderNo || 'ORD-0001'}</Text>
          <Text>Referred By: {order?.doctor?.name || 'Self'}</Text>
        </View>
      </View>

      <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10, textAlign: 'center' }}>
        LABORATORY REPORT
      </Text>

      <View style={styles.table}>
        <View style={styles.tableRow}>
          <View style={styles.tableColHeader}><Text style={styles.tableCell}>Parameter</Text></View>
          <View style={styles.tableColHeader}><Text style={styles.tableCell}>Result</Text></View>
          <View style={styles.tableColHeader}><Text style={styles.tableCell}>Unit</Text></View>
          <View style={styles.tableColHeader}><Text style={styles.tableCell}>Reference Interval</Text></View>
        </View>
        
        {/* Sample row for layout */}
        <View style={styles.tableRow}>
          <View style={styles.tableCol}><Text style={styles.tableCell}>Hemoglobin</Text></View>
          <View style={styles.tableCol}><Text style={[styles.tableCell, { fontWeight: 'bold' }]}>14.5</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>g/dL</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>13.0 - 17.0</Text></View>
        </View>
      </View>

      <View style={styles.signatureSection}>
        <View style={styles.signature}>
          <Text>Dr. Authorized Signatory</Text>
          <Text style={{ fontSize: 8 }}>MD Pathology</Text>
        </View>
      </View>

      <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
        `Page ${pageNumber} of ${totalPages} - Generated by Pathology LIS`
      )} fixed />
    </Page>
  </Document>
);
